stream/urls.py
from . import views
from . views import (
    VideoDetailView, 
    UserVideoListView, 
    VideoCreateView, 
    GeneralVideoListView, 
    VideoUpdateView,
    VideoDeleteView,
)
from django.urls import path 


app_name = "stream"

urlpatterns = [
    path('',GeneralVideoListView.as_view(), name="video-list"),
    path('video/<int:pk>/', VideoDetailView.as_view(), name="video-detail"),
    path('video/<int:pk>/update/', VideoUpdateView.as_view(), name="video-update"),
    path('video/<int:pk>/delete/', VideoDeleteView.as_view(), name="video-delete"),
    path('user/<str:username>', UserVideoListView.as_view(), name="user-videos"),
    path('video/new/',VideoCreateView.as_view(), name="video-create"),
    path('search',views.search,name="search"),
]

video_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views
from streamers import views as streamers_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('stream.urls')),
    path('profile',streamers_views.profile, name="profile"),
    path('register/',streamers_views.register, name="register"),
    path('login', auth_views.LoginView.as_view(template_name='streamers/login.html'), name="login"),
    path('logout',auth_views.LogoutView.as_view(template_name='streamers/logout.html'), name="logout"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stream/models.py
from django.db import models
from django.utils import timezone 
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class VidStream(models.Model):
    streamer = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    description = models.TextField(max_length=600)
    upload_date = models.DateTimeField(default=timezone.now)
    video = models.FileField(upload_to='')


    def __str__(self):
        return self.title 

    def get_absolute_url(self):
        return reverse("video-detail", kwargs={"pk": self.pk})

streamers/models.py
from django.db import models
from django.contrib.auth.models import User 
from PIL import Image 

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="mountain.jpg", upload_to='profile-pics')


    def __str__(self):
        return f"{self.user.username} Profile "

    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

    

stream/forms.py
from django import forms 
from . models import VidStream

class VidUploadForm(forms.ModelForm):

    class Meta:
        model = VidStream
        fields = ["title","description", "video"]

streamers/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . models import Profile 


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username','email']


class UserProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile 
        fields = ['image']

stream/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . models import VidStream
from . forms import VidUploadForm
from django.views.generic import DetailView, DeleteView, UpdateView, ListView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User 

class VideoDetailView(DetailView):
    template_name = "stream/video-detail.html"
    model = VidStream

class GeneralVideoListView(ListView):
    model = VidStream
    template_name = 'stream/video-list.html'
    context_object_name = 'videos'
    ordering = ['-upload_date']

def search(request):
    if request.method == "POST":
        query = request.POST.get('title', None)
        if query:
            results = VidStream.objects.filter(title__contains=query)
            return render(request, 'stream/search.html',{'videos':results})
    
    return render(request, 'stream/search.html')



class VideoCreateView(LoginRequiredMixin   ,CreateView):
    model = VidStream
    success_url = "/"
    template_name = 'stream/post-video.html'
    fields = ['title', 'description','video']


    #this is to make sure that the logged in user is the one to upload the content
    def form_valid(self, form):
        form.instance.streamer = self.request.user 
        return super().form_valid(form)


class VideoUpdateView(LoginRequiredMixin, UserPassesTestMixin ,UpdateView):
    model = VidStream
    template_name = 'stream/post-video.html'
    success_url = "/"
    fields = ['title','description','video']


    #this is to make sure that the logged in user is the one to upload the content
    def form_valid(self, form):
        form.instance.streamer = self.request.user 
        return super().form_valid(form)
    #this function prevents other people from updating your videos
    def test_func(self):
        video = self.get_object()
        if self.request.user == video.streamer:
            return True
        return False
    
    


class VideoDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = "stream/video-confirm-delete.html"
    success_url = "/"
    model = VidStream

    def test_func(self):
        video = self.get_object()
        if self.request.user == video.streamer:
            return True
        return False 



class UserVideoListView(ListView):
    model = VidStream
    template_name = "stream/user_videos.html"
    context_object_name = 'videos'

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return VidStream.objects.filter(streamer=user).order_by('-upload_date')
    

streamers/views.py
from django.shortcuts import render, redirect  
from django.contrib.auth.decorators import login_required 
from . forms import UserRegistrationForm, UserUpdateForm, UserProfileUpdateForm, UserProfileUpdateForm


def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserRegistrationForm()
    return render(request, 'streamers/register.html', {"form":form })

@login_required
def profile(request):
    if request.method == "POST":
        userform = UserUpdateForm(request.POST, instance=request.user)
        profileform = UserProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            profileform.save()
            return redirect("profile")
    else:
        userform = UserUpdateForm(instance=request.user)
        profileform = UserProfileUpdateForm(instance=request.user.profile)

    context = {
        'userform': userform,
        'profileform': profileform
    }
    return render(request, 'streamers/profile.html', context)   

stream/templates/stream/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Video App</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>
  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'stream:video-list' %}">Video App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-nav">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'stream:video-create' %}">New Video</a>
            <a class="nav-item nav-link" href="{% url 'stream:search' %}">Search</a>
            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
          {% endif %}
        </div>
        
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="btn btn-outline-info btn-md" href="{% url 'profile' %}">Profile</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container" id="app">
    
        {% block content %}
        {% endblock %}
    </div>
    <!-- /.container -->

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

stream/templates/stream/post-video.html
{% extends 'stream/base.html'%}
{% block content %}
    <div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h1>Upload a video</h1>
                {{ form.as_p }}
            <button class="btn btn-outline-info" type="submit">Upload</button>

        </form>
    </div>
{% endblock content %}

stream/templates/stream/search.html
{% extends 'stream/base.html'%}
{% block content %}
    <div class="center_journal">
        <h1>Search </h1>
    </div>
    <div>
        <form method="POST">
            {% csrf_token %}
            <div class="input-group">
                <div class="input-group-prepend">
                <span class="input-group-text"></span>
                </div>
                <input type="text" class="form-control" name="title">
                <button type="submit" class="btn btn-dark">Search</button>
            </div>


        </form>
    </div>
    <div>
        {% for item in videos%}
        <div class="card" style="width: 40rem; margin: 20px; box-shadow: 12em;">
            <img class="rounded-circle border-dark" src="{{ item.streamer.profile.image.url }}" style="border-color: red;" width="30" height="30">
            <a class="mr-2" href="{% url 'stream:user-videos' item.streamer.username %}" style="text-align: start;">{{ item.streamer }}</a>
            <h12 style="text-align: start;">{{ item.upload_date }}</h12>
            <video class="card-image-top" controls>
                <source src="{{ item.video.url }}" type="video/mp4">
            </video>
            <div class="card-body">
              <h5 class="card-title"><a href="{% url 'stream:video-detail' item.id  %}">{{ item.title }}</a></h5>
              <p class="card-text">{{item.description }}</p>
            </div>
            <hr>
          </div>
        {% endfor %}
    </div>
{% endblock content %}

stream/templates/stream/user_videos.html
{% extends 'stream/base.html'%}
{% block content %}
    <div>
        {% for item in videos %}
        <h3>Video belonging to {{ item.streamer.username }}</h4>
        <h4><a href="{% url 'stream:video-detail' item.id %}">{{ item.title }}</a></h1>
        <h12>{{ item.upload_date}}</h12>
        <p>{{ item.description}}</p>
        <video controls>
            <source src="{{ item.video.url }}" type="video/mp4">
          </video>
          
        {% endfor %}
    </div>
{% endblock content %}

stream/templates/stream/video-confirm-delete.html
{% extends 'stream/base.html'%}
{% block content %}
    <div style="margin-top: 1%;">
        <form method="POST">
            {% csrf_token %}
            <h3>Are you sure you want to delete the video {{ object.title }} ?</h3>
            <button type="submit" class="btn btn-primary">Confirm Delete</button>
            <a href="{% url 'stream:video-detail' object.id %}" class="btn btn-primary">Cancel</a>
        </form>
    </div>
{% endblock content %}

stream/templates/stream/video-detail.html
{% extends 'stream/base.html' %}
{% block content %}
    <div>
        <img class="rounded-circle border-dark" src="{{ object.streamer.profile.image.url }}">
        <h12>{{ object.streamer.username }}</h12>
    </div>
    <div>
        <h1>{{ object.title }}</h1>
        <h12>The video was uploaded on {{ object.upload_date }}</h12>
        <p>{{ object.description}}</p>
        {% if object.streamer == user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'stream:video-update' object.id %}">Update</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'stream:video-delete' object.id %}">Delete</a>
            </div>
        {% endif %}
        <video controls>
            <source src="{{ object.video.url }}" type="video/mp4">
        </video>
        
    </div>
{% endblock content %}

stream/templates/stream/video-list.html
{% extends 'stream/base.html'%}
{% block content %}
    <div>
        <h1>Video App </h1>
    <div>
        {% for item in videos%}
        <div class="card" style="width: 40rem; margin: 20px; box-shadow: 12em;">
            <img class="rounded-circle border-dark" src="{{ item.streamer.profile.image.url }}" style="border-color: red;" width="30" height="30">
            <a class="mr-2" href="{% url 'stream:user-videos' item.streamer.username %}" style="text-align: start;">{{ item.streamer }}</a>
            <h12 style="text-align: start;">{{ item.upload_date }}</h12>
            <video class="card-image-top" controls>
                <source src="{{ item.video.url }}" type="video/mp4">
              </video>
            <div class="card-body">
              <h5 class="card-title"><a href="{% url 'stream:video-detail' item.id  %}">{{ item.title }}</a></h5>
              <p class="card-text">{{item.description }}</p>
            </div>
            <hr>
          </div>
        {% endfor %}
    </div>
{% endblock content %}

streamers/templates/streamers/login.html
{% extends 'stream/base.html'%}
{% block content%}
    <form method="POST">
        {% csrf_token %}
        <h1>Log in</h1>
        {{ form.as_p }}
        <button class="btn btn-outline-info" type="submit">Login</button>

    </form>
    <div>
        Need an Account ?<a href="{% url 'register'%}">Register</a>
    </div>
{% endblock content %}

streamers/templates/streamers/logout.html
{% extends 'stream/base.html' %}
{% block content %}
<h2>You have been logged out</h2>
    <div>
        <a href="{% url 'login' %}">Log in again</a>
    </div>
{% endblock content %}

streamers/templates/streamers/profile.html
{% extends 'stream/base.html'%}
{% block content %}
    <div>
        <img src="{{ user.profile.image.url }}">
        <h3>{{ user.username }}</h3>
        <p>{{ username.email }}</p>
    </div>
    <div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <legend>profile info</legend>
            {{ userform.as_p }}
            {{ profileform.as_p }}
            <button class="btn btn-outline-info" type="submit">Update</button>
        </form>
        
    </div>
    
{% endblock content %}

streamers/templates/streamers/register.html
{% extends 'stream/base.html'%}
{% block content %}
    <div>
        <form method="POST">
            {% csrf_token %}
            <h1>Register</h1>
            {{ form.as_p }}
            <button class="btn btn-outline-info" type="submit">Sign Up</button>

        </form>
        <div>
            Already have an account <a href="{% url 'login' %}">Sign In</a>
        </div>
    </div>
{% endblock content %}